"""各文书类型的结构化 JSON 字段定义（与 seed_platform_pack 模板字段对齐）。"""

from __future__ import annotations

# doc_type -> { field_key: "中文说明" }
STRUCTURED_FIELD_SCHEMAS: dict[str, dict[str, str]] = {
    "application": {
        "arbitration_commission": "劳动争议仲裁委员会全称",
        "applicant_name": "申请人姓名",
        "applicant_id": "申请人身份证号",
        "applicant_address": "申请人住址",
        "applicant_phone": "申请人联系电话",
        "respondent_name": "被申请人（用人单位）名称",
        "respondent_address": "被申请人住所地",
        "respondent_legal_rep": "法定代表人",
        "requests": "仲裁请求（分项，每项一行或编号）",
        "facts": "事实与理由中的事实部分",
        "legal_basis": "法律依据（具体条文）",
        "evidence": "证据目录说明",
        "sign_date": "申请日期，格式：XXXX年XX月XX日",
    },
    "labor_supervision": {
        "complainant_name": "投诉人姓名",
        "complainant_id": "投诉人身份证号",
        "complainant_phone": "联系电话",
        "employer_name": "被投诉用人单位名称",
        "employer_address": "用人单位地址",
        "items": "投诉事项（欠薪、社保、加班等）",
        "facts": "事实经过",
        "evidence": "证据说明",
        "relief": "请求人社部门查处的事项",
        "sign_date": "日期",
    },
    "wage_demand_letter": {
        "employer_name": "致：用人单位名称",
        "employment": "入职时间、岗位、约定工资",
        "arrears": "欠薪期间与金额（元）",
        "deadline": "限期支付天数",
        "sign_date": "日期",
    },
    "forced_termination_notice": {
        "employer_name": "致：用人单位名称",
        "facts": "用工事实摘要",
        "article38_reasons": "劳动合同法第三十八条情形",
        "effective_date": "解除生效日期",
        "sign_date": "通知日期",
    },
    "arbitration_authorization": {
        "principal": "委托人（劳动者）",
        "agent": "受托人姓名",
        "agent_capacity": "受托人身份（律师/公民代理）",
        "scope": "代理权限",
        "term": "委托期限",
        "sign_date": "日期",
    },
    "evidence_list": {
        "case_ref": "案号或仲裁案号",
        "submitter": "提交人",
        "items": "证据列表：序号、名称、形式、页数、证明目的（每项一行）",
        "sign_date": "日期",
    },
    "complaint": {
        "court_name": "受理法院全称",
        "plaintiff_name": "原告姓名",
        "plaintiff_id": "原告身份证号",
        "plaintiff_address": "原告住所地",
        "plaintiff_phone": "原告联系电话",
        "defendant_name": "被告（用人单位）名称",
        "defendant_address": "被告住所地",
        "defendant_legal_rep": "法定代表人",
        "arbitration_info": "劳动仲裁前置：仲裁机构、案号、裁决摘要",
        "claims": "诉讼请求（分项）",
        "facts": "事实与理由",
        "evidence": "证据清单",
        "mediation_willing": "是否同意先行调解（是/否）",
        "sign_date": "起诉日期",
    },
    "answer": {
        "court_name": "法院名称",
        "case_number": "案号",
        "respondent_name": "答辩人",
        "defense_points": "对诉讼请求的逐项答辩",
        "facts": "事实与理由",
        "sign_date": "日期",
    },
    "appeal": {
        "court_name": "上诉法院",
        "first_instance": "一审法院、案号、裁判日期",
        "appellant": "上诉人",
        "appellee": "被上诉人",
        "appeal_requests": "上诉请求",
        "reasons": "上诉理由",
        "sign_date": "日期",
    },
    "agency_opinion": {
        "agent_info": "代理人及代理权限",
        "facts_opinion": "事实认定意见",
        "law_opinion": "法律适用意见",
        "focus": "争议焦点分析",
        "conclusion": "代理意见总结",
        "sign_date": "日期",
    },
    "legal_opinion": {
        "recipient": "致送单位或个人",
        "background": "事实背景",
        "analysis": "法律分析",
        "opinion": "结论性意见",
        "sign_date": "日期",
    },
    "lawyer_letter": {
        "recipient": "收函人",
        "law_firm": "律师事务所",
        "facts": "事实陈述",
        "demands": "律师要求",
        "consequences": "法律后果告知",
        "sign_date": "日期",
    },
    "preservation_application": {
        "court_name": "受理法院",
        "applicant": "申请人",
        "respondent": "被申请人",
        "preservation_target": "保全财产范围及金额",
        "reasons": "事实与理由",
        "guarantee": "担保情况",
        "sign_date": "日期",
    },
    "labor_contract": {
        "employer_name": "甲方用人单位",
        "employer_address": "甲方住所",
        "employer_rep": "甲方法定代表人",
        "employee_name": "乙方劳动者",
        "employee_id": "乙方身份证号",
        "employee_address": "乙方住址",
        "term_type": "合同期限类型",
        "term_dates": "起止日期",
        "probation": "试用期约定",
        "job_position": "工作岗位",
        "work_location": "工作地点",
        "job_duties": "工作内容",
        "work_hours": "工时制度",
        "rest_leave": "休息休假",
        "wage_standard": "工资标准",
        "pay_date": "工资支付日期",
        "social_insurance": "社会保险",
        "benefits": "福利待遇",
        "labor_protection": "劳动保护与职业危害防护",
        "confidentiality": "保密竞业等约定",
        "training": "培训服务期",
        "delivery_address": "送达地址",
        "change_termination": "变更解除终止",
        "dispute_resolution": "争议解决方式",
        "sign_date": "签订日期",
    },
    "contract": {
        "party_a": "甲方",
        "party_b": "乙方",
        "subject": "合同标的",
        "price": "价款及支付",
        "performance": "履行期限地点方式",
        "breach": "违约责任",
        "dispute": "争议解决",
        "sign_date": "签订日期",
    },
    "mediation": {
        "mediation_org": "调解组织",
        "party_worker": "劳动者",
        "party_employer": "用人单位",
        "dispute_summary": "争议概述",
        "payment": "款项金额构成支付",
        "other_obligations": "其他义务",
        "finality": "终局解决条款",
        "breach_liability": "违约责任",
        "effective_clause": "生效条件",
        "sign_date": "日期",
    },
    "settlement_agreement": {
        "employer": "用人单位（甲方）",
        "worker": "劳动者（乙方）",
        "settlement_amount": "和解对价总额及构成",
        "payment_terms": "支付期限与账户",
        "mutual_release": "权利放弃与终局条款",
        "breach": "违约责任",
        "sign_date": "签订日期",
    },
}


def schema_prompt_block(doc_type: str) -> str:
    fields = STRUCTURED_FIELD_SCHEMAS.get(doc_type)
    if not fields:
        return "{}"
    lines = ["{"]
    for key, desc in fields.items():
        lines.append(f'  "{key}": "",  // {desc}')
    lines.append("}")
    return "\n".join(lines)
